<!-- Button.stories.svelte -->
<script module>
  import { defineMeta } from '@storybook/addon-svelte-csf';
  import Button from './Button.svelte';
  import { fn } from '@storybook/test'; // optional; used to track onClick in Storybook

  /**
   * Using defineMeta to configure our stories. 
   * The `tags: ['autodocs']` enable automatic Docs generation
   * (including code snippets) in Storybook 7.
   */
  const { Story } = defineMeta({
    title: 'Example/Button',
    component: Button,
    tags: ['autodocs'],

    // Define controls for each prop
    argTypes: {
      type: {
        control: { type: 'select' },
        options: ['primary', 'secondary', 'tertiary'],
      },
      label: { control: 'text' },
      leadingIcon: {
        control: { type: 'select' },
        options: ['none', 'envelope', 'lock', 'user', 'close'],
      },
      trailingIcon: {
        control: { type: 'select' },
        options: ['none', 'chevronDown', 'chevronRight', 'download'],
      },
      size: {
        control: { type: 'select' },
        options: ['default', 'small', 'large'],
      },
      customIcon: {
        control: { type: 'select' },
        options: ['default', 'icon-only'],
      },
    },

    // Provide default args, including an onClick mock if desired
    args: {
      label: 'Button',
      // onClick: fn(),
    }
  });
</script>

<!-- 
  Stories below. Each <Story /> can have a unique "name" and "args".
  The code snippet is auto-generated by Storybook’s autodocs for each story.
-->

<Story
  name="Primary"
  args={{ type: 'primary', label: 'Primary Button' }}
/>

<Story
  name="Secondary"
  args={{ type: 'secondary', label: 'Secondary Button' }}
/>

<Story
  name="Tertiary"
  args={{ type: 'tertiary', label: 'Tertiary Button' }}
/>

<Story
  name="Small"
  args={{ size: 'small', label: 'Small Button' }}
/>

<Story
  name="Large"
  args={{ size: 'large', label: 'Large Button' }}
/>

<Story
  name="Icon Only (Envelope)"
  args={{
    customIcon: 'icon-only',
    leadingIcon: 'envelope',
    label: 'Icon Button'
  }}
/>
